### ISSUE TITLE
Regarding replit bounty: Product Information Retrieval and Customer Query Answering

### ISSUE THREAD

**Issue by netpoe** [AdonisCodes/AdonisCodes#1]
https://replit.com/bounties/@JohnH31/product-information

Hey, Adonis. I saw you applied to this bounty on Replit.

I developed https://fileagent.ai/, perhaps you want to join forces? File Agent manages multiple LLM's to formulate queries of any API.

I sent a Discord friend request -> n***oe

**Comment by AdonisCodes** [comment]
Have sent a message.
Thanks!
